# https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Use Node
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      # Cache
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Install
      - name: Install
        run: npm install
      # Build
      - name: Build
        run: |
          CONTEXT=production npm run build
        env:
          VITE_GITHUB_RUN_NUMBER: ${{github.run_number}}
          VITE_GITHUB_SHA: ${{github.sha}}
      # Validate
      - name: Validate
        run: npm run validate
      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: dist
          path: dist
      # Deploy Preview
      - name: Deploy Preview
        if: github.ref != 'refs/heads/master' && github.event.repository.fork == false
        run: npm run deploy:preview -- --auth ${{secrets.NETLIFY_AUTH_TOKEN}} --alias $GITHUB_RUN_ID
      # Deploy Production
      - name: Deploy Production
        if: github.ref == 'refs/heads/master' && github.event.repository.fork == false
        run: npm run deploy:prod -- --auth ${{secrets.NETLIFY_AUTH_TOKEN}}
